import { AspectRatio } from "@/components/ui/aspect-ratio";
import { Card } from "@/components/ui/card";
import { MessageCircle } from "lucide-react";
import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function Home() {
    // const res = await fetch(`${process.env.APP_URL}/api/valve/vitality`, {
    //     next: { revalidate: 60 },
    // })
    //
    // if (!res.ok) console.log('pas res')
    //
    // const data = await res.json()

    return (
        <Card className="bg-muted w-full max-w-5xl h-fit rounded-lg !p-0 divide-y !gap-0">
            {[...Array(5)].map((_, i) => (
                <article key={i} className="flex gap-5 p-5">
                    <div className="w-50">
                        <AspectRatio ratio={18 / 12} className="bg-muted">
                            <Image
                                src="https://images.unsplash.com/photo-1588345921523-c2dcdb7f1dcd?w=800&dpr=2&q=80"
                                alt="Photo by Drew Beamer"
                                fill
                                className="h-full w-full rounded-md object-cover"
                            />
                        </AspectRatio>
                    </div>

                <div className="flex flex-col gap-2 w-full">
                    <div className="flex items-center justify-between text-sm text-muted-foreground">
                        <p>Il y a 4 heures</p>

                        <span className="flex gap-1 items-center leading-none">
                            <MessageCircle size={14} />
                            2
                        </span>
                    </div>
                    <h2 className="text-xl font-medium">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque, tempora.</h2>
                    <span className="text-sm text-muted-foreground">tag, tag</span>
                    </div>
                </article>
            ))}
        </Card>
    );
}
