import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function Home() {
    const res = await fetch(`${process.env.APP_URL}/api/valve/vitality`, {
        next: { revalidate: 60 },
    })

    if (!res.ok) console.log('pas res')

    const data = await res.json()

    return (
        <div>
            {JSON.stringify(data, null, 2)}
        </div>
    );
}
